### PR TITLE
OpenNI driver for Orbbec cameras

### PR DESCRIPTION
**Pull request by Robzz**
I'm currently working on adding support for the Orbbec Astra pro camera to fw4spl, which is implemented in [Orbbec's fork of OpenNI](https://github.com/orbbec/OpenNI2/tree/orbbec-dev). In addition, I'll need to make a small change to the OpenNI patch and CMakelists in the fw4spl-deps repo. It's ready and only waiting for this to be merged.

This PR adds 12 commits from Orbbec regarding the OpenNI driver. The previous 10 commits are from [upstream's `develop` branch](https://github.com/occipital/OpenNI2/commits/develop) on which Orbbec's work is based.

### CODE REVIEW

**Review by schweitzer — COMMENTED** [review]
I think the only review we can do here is to test if we are still able to grab images from kinect/e-sense sensors...

**Comment by Robzz** [comment]
Since I noticed you guys went on a merging spree today, just in case, please don't merge this just yet, I'm working on supporting the camera on Linux and there's one more thing I need to add tomorrow, the [udev rules file](https://github.com/orbbec/astra/blob/master/install/orbbec-usb.rules).

The good news is, at first glance, the Sense camera seems to still be working with this both on Windows and Linux.

**Review by greenjava — CHANGES_REQUESTED** [review]
Ok, but I didn't find "_orbbec_" device target in MSVS solution _OpenNI.sln_ (whereas _orbbec.vcxproj_ project was added).

**Comment by greenjava** [comment]
This PR has been merged into a dedicated branch (fix/binpkgs: https://github.com/fw4spl-org/OpenNI2/commit/18ab2af9f145f023c847e667074bacf971fc95ea).

Thanks for your contribution 👍

**Pull request closed without merging**
